### ISSUE TITLE
Some rationales have issues with newlines

### ISSUE THREAD

**Issue by stoperro** [kaistAI/CoT-Collection#2]
Example:
```
"rationale": "Given the list ['J', 'y', '5075', '7149', '3081', 'E', 'H', 'Q', 'Z','s','a','M','839','q','5839','C','5503','B','i']n1. The 3rd element is 5075.n2. The 4th element is 7149.n3. The 5th element is 3081.n4. The 14th element is 839.' 5. The 15th element is q and it will be treated as 0 during final calculation due to non-number string characters inside the brackets of list.. 6.The 16th element is 5839. 7.The 17th element is C and it will be treated as 0 during final calculation due to non-number string characters inside the brackets of list.. 8.The 18st element i 5503..",
```

So it shouldn't be e.g. `The 4th element is 7149.n3. The 5th element is 3081.` but `The 4th element is 7149.\n3. The 5th element is 3081.` (character `\` added before `n`).

Even stranger: `The 14th element is 839.' 5. The 15th element is`, suddenly instead of `\n` there is `' `.

**Comment by stoperro** [comment]
Similar:
```
"rationale": "To simplify the problem, we can use the following steps:n1. d = (0 - 1)/((-1)/7) = 2/7n2. t = 2 + -1 = 1n3. b= (-4 + 2 + d/t) = (-4 + 2 + 14) = 10n4. Solving for m and z in the system of equations: nm*(2-z)+(5-z)*(-6+z2)=0 nz*(6-z)=m*(-2+z)+5-z We get two roots: m=-3, z=-1 and m=11, z=9",
```

**Comment by joocjun** [comment]
Thanks @stoperro for pointing out the problem. We are also aware of the problem you mentioned and think that it's a situation highly related to the model(codex) we used for rationale generation. But due to limited resource and time, and also in terms of reproducability of reported results, we've decided to release the data as it is for now. 

As many recent models report enhanced abilities based upon the improvement of data quality, we also expect further improvment through cleansing potentially problematic factors.

**Comment by SeungoneKim** [comment]
@stoperro Thank you for your interest in our paper!
As LMs get more powerful, they are becoming more robust to simple differences such as the pattern you mentioned. I recommend checking out this insightful twitter post as well:) 

https://twitter.com/_jasonwei/status/1664367044794662912

I've also updated the two instances you've mentioned!
